### ISSUE TITLE
Checkpoint 1

### ISSUE THREAD

**Issue by JBostroem96** [JBostroem96/indieProject#1]
@pawaitemadisoncollege I'd appreciate any feedback so far! Thank you.

**Comment by pawaitemadisoncollege** [comment]
Hi @JBostroem96 ! 

Thanks for sharing your indie project checkpoint 1! 

Following are my observations and suggestions:

**Problem statement**

Does a good job laying out the problem and explaining how your application solves it.

- [ ] Consider adding a Technology list - it might be helpful for those viewing your readme.md to be able to quickly understand the technologies and version are used in the project.  


**User Stories**

Your options for filtering do a good job providing the type of information somebody would want to see.  

- [ ] I think it would make sense to allow any user to view data, while only a registered/logged in user could alter data.
- [ ] "Add race" versus "add result". When I think of adding a _race_ - I think of the whole _event_.  The information for a race (event) would include the event/race name, date, and length in number of hours.
- [ ] The other thing that will need to be entered are _results_ - how did each team do?  That entry would include: team name, division, and place in the division. 
- [ ] Considering that language, I think the user stories could be improved to more clearly identify what is being CRUD'd - a race or a result.

**Reflection statements/Time Log**

Great work consistently tracking!

**Project Plan**

A good start - need to add tasks for the remaining weeks.

**Other**

I'm attaching an example of the spreadsheet race directors send me. There are two ways this could be processed: 1) upload the spreadsheet (csv file) and let the program parse the information, or 2) manually enter it. I think your user stories indicate you are going to have somebody manually enter each one, which is a-ok, but wanted to toss the uploading of the css file out there as an option. 

The important information includes: the race name, the team name, their division, and their place within that division. 
[WIARS - 2023 - Winter RMAC Race Results - 3 Hour.xlsx](https://github.com/JBostroem96/indieProject/files/14226366/WIARS.-.2023.-.Winter.RMAC.Race.Results.-.3.Hour.xlsx)
